### ISSUE TITLE
Replace npm install with npm ci for Node projects

### ISSUE THREAD

**Issue by Maximization** [lade-io/jet#2]
Hey! Cool project 🌟

I took it out for a spin on a sample NodeJS project and was surprised with the result, very nice. It spewed the following output:
```dockerfile
FROM node:13.8.0

WORKDIR /app/

COPY package.json package-lock.json /app/
RUN npm install

COPY . /app/

CMD ["node", "index.js"]
```

May I suggest replacing `npm install` with `npm ci` if it detects package-lock.json?

Also a nit improvement is to get rid of `/app/` in both COPY instructions since WORKDIR is already set. Unless you deliberately chose this for some reason.

Are you open for other best practices suggestions, such as running as non-root? Let me know and I'll create separate issues.

Keep up the good work!

**Comment by beornf** [comment]
Thanks for trying out jet! 💯 

I've been looking into `npm ci` and learned it was introduced in npm v6. With some testing of Node images `npm ci` seems to be present in all versions of node >= 10.3. For images with npm v5 (i.e. node < 10.3) the additional step `npm install -g npm` should be added.

You are right having `/app/` every time is a bit verbose. I thought may look clearer but you stay in the workdir anyway.

Feel free to create more issues for best practices. Running as non-root would be applicable to other languages too.

**Comment by Maximization** [comment]
>I've been looking into npm ci and learned it was introduced in npm v6. With some testing of Node images npm ci seems to be present in all versions of node >= 10.3. For images with npm v5 (i.e. node < 10.3) the additional step npm install -g npm should be added.

Ah yeah, that's true. Not sure whether it's a good idea to use a different NPM version. I remember a couple releases at the end of 5 and going into 6, NPM broke badly between releases. I'd understand if you want to keep it like this to support older versions of Node.

>Feel free to create more issues for best practices. Running as non-root would be applicable to other languages too.

Nice, I'll make an issue tomorrow. I've never done Go so sorry for not opening a PR instead.

**Comment by beornf** [comment]
Yeah sounds like it would be safer to only support `npm ci` for versions of node >= 10.3 then. It's unlikely anyone is still using node versions more than 2 years old. Making a note to update the node versions in the test cases too.

**Comment by Maximization** [comment]
Fyi, Node 8.12 until 8.17 also ships with NPM 6 https://nodejs.org/en/download/releases/

**Comment by beornf** [comment]
Great link! Now I can just check there to see which version of NPM would be present.
