### ISSUE TITLE
Use non-root user for NodeJS projects

### ISSUE THREAD

**Issue by Maximization** [lade-io/jet#3]
It's [recommended](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user) to run Node inside the container as non-root user. The Node Docker images provide a `node` user just for that.

In addition, it's good to have the project folder owned by the same user that's going to run the process to avoid permission issues when writing/reading to/from files from inside the app.

```dockerfile
FROM node:<version>

USER node
RUN mkdir /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package-lock.json package.json ./
RUN npm ci
COPY --chown=node:node . .

CMD ["node", "index.js"]
```

Few changes from the Dockerfile generated by Jet and this one:

1. The `node` user doesn't have permissions to create/own the`/app` folder so `/home/node/app` is the project root
2. `RUN mkdir /home/node/app` - we create the directory in a separate command because WORKDIR will use `root` to create the directory if it doesn't exist. This instruction doesn't take a flag to change that unfortunately
3. `--chown=node:node` - COPY also uses `root` by default to add files to the image, we make it so it uses the `node` user and group

Let me know what you think

**Comment by beornf** [comment]
Will be pushing a commit that makes these changes soon. Unless you want to review the PR first?

The Jet generated output for a Node test case is:
```dockerfile
FROM node:12.16.1

USER node

RUN mkdir /home/node/app/

WORKDIR /home/node/app/

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

COPY --chown=node:node . ./

CMD ["node", "server.js"]
```
I'm still working on supporting non-root user for Golang, Python and Ruby packs.

Also optimized the Docker tag lookup which is a bottleneck and was timing out during my testing.

**Comment by beornf** [comment]
It would be safer to write `mkdir -p /home/node/app` as it creates the parent directory if it doesn't exist. However it's not required as we know `/home/node` is present in the node base image. What's your opinion? Either way seems fine to me.

**Comment by Maximization** [comment]
Sorry for the late reply.

The Dockerfile output looks good! Good job. Most of the examples I've seen online don't use the `-p` flag. On the other hand I agree with you it's safer, but unlikely the Node base image will remove the `--create-home` flag when they create the Node user. Either way is fine with me too.
